{% set name = "gwvet" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "76db8c29b2140a38d0dbf426040a3c5fe91a0b2eb18822861f054df91bc8c352"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy >=3.0.0
    - decorator
    - dqsegdb
    - gwdetchar >=2.0.0
    - gwpy >=2.0.0
    - gwsumm >=2.0.0
    - gwtrigfind
    - lscsoft-glue >=1.60.0
    - markuppy
    - matplotlib-base >=3.1.0
    - numpy >=1.16
    - python >=3.6
    - scipy >=1.2.0

test:
  imports:
    - gwvet
    - gwvet.cli
    - gwvet.etg
    - gwvet.hug
    - gwvet.metric
    - gwvet.segments
    - gwvet.tabs
    - gwvet.triggers
    - gwvet.vdf
  commands:
    # check scripts run ok
    - python -m gwvet --help
    - python -m gwvet.hug --help
    - python -m gwvet.vdf --help

about:
  home: "https://github.com/gwpy/vet"
  doc_url: "https://github.com/gwpy/vet/blob/master/README.rst"
  dev_url: "https://github.com/gwpy/vet"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary: "Gravitational-wave Veto Evaluation and Testing suite"
  description: |
    GWVET is an extension to the python toolbox GWSumm, used by the LIGO
    Scientific Collaboration to review and evaluate data-quality veto products

extra:
  recipe-maintainers:
    - alurban
    - areeda
    - duncanmmacleod
    - eagoetz
    - robertbruntz
